### ISSUE TITLE
Font alignment?

### ISSUE THREAD

**Issue by HaydenHildreth** [HaydenHildreth/easy_clock#1]
I should try to add this to the configuration file... It could be 1-2 fields. X and Y value for location within the Tkinter main window.

**Comment by mimeosd** [comment]
Please give more details on what is needed? Random positions for X and Y ?

**Comment by HaydenHildreth** [comment]
> Please give more details on what is needed? Random positions for X and Y ?

Not necessarily "random" positions for X and Y per say, but rather, let the user decide where upon the screen they're displayed. i.e. Like for whatever reason if I wanted it to be aligned to the center top of the window.

Currently, it is just set to ALWAYS display in the middle of this screen by determining the screen size and dividing in half in both ways like below:

x_val = root.winfo_width() / 2
y_val = root.winfo_height() / 2

**Comment by mimeosd** [comment]
Made a PR check it out.

**Comment by HaydenHildreth** [comment]
Your PR was absolute perfect and a very elegant solution to this "problem" or enhancement! I very much appreciate it, I've gone ahead and pulled it into the main branch, I've just changed the default ANCHOR value to be center in both Main and Configuration file.

Thank you! 
Committed in: d4ad44c
